### ISSUE TITLE
Cannot get it to work for Sapper

### ISSUE THREAD

**Issue by mhatvan** [AlexxNB/svelte-preprocess-markdown#13]
I tried out your provided example in https://github.com/AlexxNB/svelte-preprocess-markdown/issues/12 and it works perfectly with pure Svelte. 

Can you provide an example of how to combine it with Sapper? 

No matter what I try, I cannot import modules and variables are not getting executed.

**Comment by mhatvan** [comment]
I can actually get it to work when importing a `.md` file directly into e.g. `<App />`.

Unfortunately, I am never importing markdown files directly since it is a blog, can you take a look here?
https://github.com/mhatvan/mhatvan.github.io/blob/develop/src/routes/blog/_posts.js

**Comment by AlexxNB** [comment]
Did you add preprocessor in the both client and server sections in the `rollup.conf.js` file?

**Comment by mhatvan** [comment]
Yes, I did that. 

There are multiple other issues regarding the same topic: https://github.com/pngwn/MDsveX/issues/28, https://github.com/pngwn/MDsveX/issues/42

**Comment by TheComputerM** [comment]
Did you add the `--ext` parameter to sapper run scripts?

**Comment by mhatvan** [comment]
Yes, without success. 

Rendering static files does work, but in this case it is about dynamically generated files like blog posts that don't work. 

Here it is described well, mdsvex has the same issue: https://github.com/pngwn/MDsveX/issues/28#issuecomment-635120364
