### ISSUE TITLE
Import collection?

### ISSUE THREAD

**Issue by stordahl** [AlexxNB/svelte-preprocess-markdown#19]
Is it possible to import a folder of .md files, like it's shown [here](https://github.com/sveltejs/svelte/issues/3273#issuecomment-513545229) ?

**Comment by AlexxNB** [comment]
there shoud be index.js file where all `md` files are imported.

```js
export {default as Page1} from './Page1.md';
export {default as Page2} from './Page2.md';
...
```

Then just use a collection:

```js
import * as Collection from 'folder_where_index_is';
...
<Collection.Page1/>
```

Didn't check but should work as in Svelte.

**Comment by stordahl** [comment]
Yeah I'd just like a way to make this a little more dynamic without having to update a js file. Something like this...
```svelte
/* somehow create an array with all file names in md directory */
const mdArr = [ an, array, of, file, names, somehow];
...
{#each mdArr as md}
	<svelte:component this={ md } />
{/each}
```
Is there any way at all to accomplish something like this? Thank for your time!

**Comment by AlexxNB** [comment]
This is not a feature for markdown-preprocessor. You may create another preprocessor for batch import from the folders.
