### ISSUE TITLE
Escaping

### ISSUE THREAD

**Issue by jakobrosenberg** [AlexxNB/svelte-preprocess-markdown#2]
Hi, how do you escape characters like < and }?

**Comment by AlexxNB** [comment]
It is escaping only in markdowns code blocks - https://github.com/AlexxNB/svelte-preprocess-markdown/blob/master/src/handlers/code.js#L9

In other places these characters are preserved, so you can use tags and Svelte's interploations inside markdown.

**Comment by jakobrosenberg** [comment]
Thanks Alex
Any chance inline code blocks are on the horizon?

**Comment by AlexxNB** [comment]
You may use tripple quotas inline code.
```markdown
<script>
let name = 'World'
</script>
``` {name} ```       <- this will <code>&#123;name&#125;</code>
` {name} `           <- this will <code>{name}</code> and handeled by Svelte
```

**Comment by jakobrosenberg** [comment]
I'm getting errors if I include < and > brackets inline. Specifying a highlighter seems to be a requirement as well.

**Comment by AlexxNB** [comment]
Can you provide example?

**Comment by jakobrosenberg** [comment]
```
lorem ipsum ```<Foo /> ```
```
```
lorem ipsum ```html <Foo /> ```
```
````
lorem ipsum 
```
<Foo /> 
```
````

All examples above throws errors

````
lorem ipsum 
``` html
<Foo /> 
```
````

This doesn't throw an error

**Comment by AlexxNB** [comment]
Just published updated version on npm. Now < and > are replaced by & lt; and & gt;

```  
` ` ` <Foo /> ` ` ` 
Will be <code>&lt;Foo /&gt;</code>
```

```
` ` `html <Foo /> ` ` `     
Will be <code>html &lt;Foo /&gt;</code> Don't shure that lang definition there is correct syntax.
```

```
` ` `‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎
anything
` ` `
 Now it is unsupporting - use code blocks with lang definition. I have no idea how to parse it correctly. Need help! =) 
```

**Comment by jakobrosenberg** [comment]
Great! Thanks a lot.👍

**Comment by AlexxNB** [comment]
Highlighter.... you can pass to the preprocessor option:
```javascript
markdown({
    highlight: function (code,lang){...}
});
```
Look for the Marked options reference.

**Comment by AlexxNB** [comment]
Sorry, it didn't published yet, because this change broke some tests.

**Comment by AlexxNB** [comment]
OK, I repair it.  Please update to the 2.4.3 version
